---
title: "R Bootcamp - Individual Assignment"
output:
  pdf_document: default
  html_document: default
date: "2025-08-15"
---

```{r, include=FALSE}
library(here)
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)

hotness <- read_csv("data/hotness.csv")

```

## Setup

```{r}

hotness <- hotness %>%
  separate(
    zip_name, 
    into = c("city", "state"), 
    sep = ", ", 
    fill = "right", 
    remove = FALSE) %>%
  mutate(
    state = toupper(state),
    month_date = ym(as.character(month_date_yyyymm)),
    year = year(month_date),
    month  = month(month_date)
  )

```

## State Profile Summary

```{r}

state_summary <- hotness %>%
  group_by(state, year = year(month_date)) %>%
  summarise(
    median_days_on_market_sm = median(median_days_on_market, na.rm=TRUE),
    median_listing_price_sm = median(median_listing_price, na.rm=TRUE),
    .groups = "drop"
  ) %>%
  arrange(state, desc(year))
  
head(state_summary)

```

```{r}

ggplot(state_summary, aes(year, median))

```

```{r}

deep_dive <- hotness %>%
  filter(
    state %in% c("GA", "FL", "AL"),
    year %in% c(2022, 2023)
  ) %>%
  group_by(state, year) %>%
  summarise(
    median_days_on_market = median(median_days_on_market, na.rm=TRUE),
    median_listing_price = median(median_listing_price, na.rm=TRUE),
    .groups = "drop"
  ) %>%
  arrange(state, desc(year))

head(deep_dive)

```

```{r}

top_hot_rank <- hotness %>%
  group_by(state)
  summarise(avg)
```
